apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: asterisk-vpa
  namespace: asterisk
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asterisk
  updatePolicy:
    updateMode: "Auto"