apiVersion: v1
kind: Service
metadata:
  name: asterisk
  namespace: asterisk
spec:
  type: LoadBalancer
  selector:
    app: asterisk
  ports:
  - name: sip-udp
    port: 5060
    targetPort: 5060
    protocol: UDP
  - name: sip-tcp
    port: 5060
    targetPort: 5060
    protocol: TCP
  - name: rtp-start
    port: 10000
    targetPort: 10000
    protocol: UDP
  - name: rtp-end
    port: 20000
    targetPort: 20000
    protocol: UDP