apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asterisk-pvc
  namespace: asterisk
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 5Gi