apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: asterisk-vpa
  namespace: asterisk
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asterisk
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["cpu", "memory"]
        minAllowed:
          cpu: "100m"
          memory: "64Mi"
        maxAllowed:
          cpu: "2000m"
          memory: "1Gi"
