apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: asterisk-hpa
  namespace: asterisk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: asterisk
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
